name: amazon_clone
description: A starter Amazon Clone built with Flutter, Provider and Firestore.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.0
  intl: ^0.18.0
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2 
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
