// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWRy1Fh353PHDhTnFL99snErI7S-Th4a4',
    appId: '1:714271115641:web:f30f9f70b96891a43507a8',
    messagingSenderId: '714271115641',
    projectId: 'clone-65b86',
    authDomain: 'clone-65b86.firebaseapp.com',
    storageBucket: 'clone-65b86.firebasestorage.app',
    measurementId: 'G-0FRX8N4S6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIB6_nY5lLuBoPFb6eBfj6Jnk0Ptacu8M',
    appId: '1:714271115641:android:ca545ae644b3e6d83507a8',
    messagingSenderId: '714271115641',
    projectId: 'clone-65b86',
    storageBucket: 'clone-65b86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTBMp5hD9k4UD3gvH2ICGNKFX6h5cuMY',
    appId: '1:714271115641:ios:3a180df9e50ba6253507a8',
    messagingSenderId: '714271115641',
    projectId: 'clone-65b86',
    storageBucket: 'clone-65b86.firebasestorage.app',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTBMp5hD9k4UD3gvH2ICGNKFX6h5cuMY',
    appId: '1:714271115641:ios:3a180df9e50ba6253507a8',
    messagingSenderId: '714271115641',
    projectId: 'clone-65b86',
    storageBucket: 'clone-65b86.firebasestorage.app',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWRy1Fh353PHDhTnFL99snErI7S-Th4a4',
    appId: '1:714271115641:web:83698542ac418a0d3507a8',
    messagingSenderId: '714271115641',
    projectId: 'clone-65b86',
    authDomain: 'clone-65b86.firebaseapp.com',
    storageBucket: 'clone-65b86.firebasestorage.app',
    measurementId: 'G-THW6QMVEYY',
  );
}
